#!/usr/bin/env bash
# Clone/update every addon repo this stack needs, except odoo-hr-attendance
# itself -- this script lives inside that repo, so its own checkout (../) is
# mounted directly.
#
# Two groups:
#   systango/  the other three product repos
#   oca/       the 15 OCA repos those products depend on. These are NOT
#              optional: without them most module manifests have unresolved
#              `depends` and Odoo will not offer them for install.
#
# Everything tracks branch 18.0 -- there is no `main` branch on any of these
# repos. Clones are shallow; resolved commits are recorded in versions.lock
# so a deploy can be traced back to exact code.
set -euo pipefail

BRANCH="18.0"
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ADDONS="$DIR/addons"
LOCK="$DIR/versions.lock"

SYSTANGO_REPOS=(
  odoo-timesheet
  odoo-purchase-workflow
  odoo-hr-expense
)

OCA_REPOS=(
  server-ux
  server-tools
  account-invoicing
  account-analytic
  hr
  hr-holidays
  calendar
  brand
  product-attribute
  project
  reporting-engine
  sale-workflow
  stock-logistics-workflow
  stock-logistics-warehouse
  web
)

sync_repo() {
  local url="$1" target="$2" name="$3"
  if [ -d "$target/.git" ]; then
    echo "  updating $name"
    git -C "$target" fetch --depth 1 origin "$BRANCH"
    git -C "$target" checkout -q --detach FETCH_HEAD
  else
    echo "  cloning  $name"
    git clone --quiet --depth 1 --branch "$BRANCH" --single-branch "$url" "$target"
  fi
}

mkdir -p "$ADDONS/systango" "$ADDONS/oca"

echo "Syncing Systango repos (branch $BRANCH)..."
for repo in "${SYSTANGO_REPOS[@]}"; do
  sync_repo "https://github.com/SystangoTechnologies/${repo}.git" \
            "$ADDONS/systango/$repo" "$repo"
done

echo "Syncing OCA dependency repos (branch $BRANCH)..."
for repo in "${OCA_REPOS[@]}"; do
  sync_repo "https://github.com/OCA/${repo}.git" \
            "$ADDONS/oca/$repo" "OCA/$repo"
done

# Record exactly what was deployed.
{
  echo "# generated by clone.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ), branch $BRANCH"
  printf '%-46s %s\n' "SystangoTechnologies/odoo-hr-attendance" "$(git -C "$DIR/.." rev-parse HEAD)"
  for repo in "${SYSTANGO_REPOS[@]}"; do
    printf '%-46s %s\n' "SystangoTechnologies/$repo" "$(git -C "$ADDONS/systango/$repo" rev-parse HEAD)"
  done
  for repo in "${OCA_REPOS[@]}"; do
    printf '%-46s %s\n' "OCA/$repo" "$(git -C "$ADDONS/oca/$repo" rev-parse HEAD)"
  done
} > "$LOCK"

echo
echo "All addon repos synced under $ADDONS"
echo "Commits recorded in $LOCK"
